trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  flutterVersion: 'stable' # Specify the Flutter version to use (e.g., stable, 3.3.0, etc.)

steps:

# 1. Checkout the repository
- task: Checkout@1
  displayName: 'Checkout Git repository'

# 2. Install Flutter
- script: |
    git clone https://github.com/flutter/flutter.git --branch ${{ variables.flutterVersion }}
    echo "##vso[task.setvariable variable=FLUTTER_HOME]$(System.DefaultWorkingDirectory)/flutter"
    echo "export PATH=\$FLUTTER_HOME/bin:\$PATH" >> $BASH_ENV
    source $BASH_ENV
    flutter doctor
  displayName: 'Install Flutter'

# 3. Install dependencies
- script: |
    flutter pub get
  displayName: 'Install Flutter dependencies'

# 4. Build the Android app (APK file)
- script: |
    flutter build apk --release
  displayName: 'Build Android APK'

# 5. Publish the APK artifact
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'build/app/outputs/flutter-apk/' # Path to the directory containing the APK file
    ArtifactName: 'Android_Artifact'
    publishLocation: 'Container'
  displayName: 'Publish APK Artifact'
