pool:
  name: Default  # Use your self-hosted agent pool name

variables:
  flutterVersion: '3.5.3'  # Specify the Flutter version
  buildConfiguration: 'Release'  # Build configuration (Debug, Release)

steps:
# Install Flutter
- script: |
    git clone -b ${flutterVersion} --depth 1 https://github.com/flutter/flutter.git
    echo '##vso[task.prependpath]$(Pipeline.Workspace)/flutter/bin'
    flutter doctor
  displayName: 'Install Flutter'

# Clean Previous Builds
- script: flutter clean
  displayName: 'Clean Previous Builds'

# Install Dependencies
- script: flutter pub get
  displayName: 'Install Dependencies'

# Install iOS CocoaPods Dependencies
- script: |
    cd ios
    pod install
  displayName: 'Install CocoaPods Dependencies'

# Build iOS App Without Signing
- script: |
    flutter build ios --release --no-codesign
  displayName: 'Build iOS App (Unsigned)'
